allowBuilds:
  '@swc/core': true
  better-sqlite3: true
  msgpackr-extract: set this to true or false
patchedDependencies:
  '@outloud/adonis-openapi-generator': patches/@outloud__adonis-openapi-generator.patch
