services:
  # 1. The AdonisJS Backend
  - type: web
    name: sync-backend
    env: node
    buildCommand: pnpm install && node ace build
    startCommand: cd build && pnpm install --prod && node ace migration:run --force && node bin/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: LOG_LEVEL
        value: info
      - key: APP_KEY
        generateValue: true
      - key: REDIS_HOST
        fromService:
          type: redis
          name: sync-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: sync-redis
          property: port

  - type: redis
    name: sync-redis
    plan: free
    ipAllowList: []
