/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  v1: {
    auth: {
      AccessTokens: () => import('#controllers/v_1/auth/access_tokens_controller'),
      ForgotPasswords: () => import('#controllers/v_1/auth/forgot_passwords_controller'),
      NewAccount: () => import('#controllers/v_1/auth/new_account_controller'),
      ResetPasswords: () => import('#controllers/v_1/auth/reset_passwords_controller'),
      VerifyEmails: () => import('#controllers/v_1/auth/verify_emails_controller'),
    },
    core: {
      Bookmark: () => import('#controllers/v_1/core/bookmark_controller'),
      Folder: () => import('#controllers/v_1/core/folder_controller'),
      Invitation: () => import('#controllers/v_1/core/invitation_controller'),
      Member: () => import('#controllers/v_1/core/member_controller'),
    },
    oauth: {
      Googles: () => import('#controllers/v_1/oauth/googles_controller'),
    },
    users: {
      Notifications: () => import('#controllers/v_1/users/notifications_controller'),
      Profile: () => import('#controllers/v_1/users/profile_controller'),
    },
  },
}
