/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Bookmarks: () => import('#controllers/bookmarks_controller'),
  Folders: () => import('#controllers/folders_controller'),
  ForgotPassword: () => import('#controllers/forgot_password_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  ResetPassword: () => import('#controllers/reset_password_controller'),
  VerifyEmail: () => import('#controllers/verify_email_controller'),
  Members: () => import('#controllers/members_controller'),
  Invitations: () => import('#controllers/invitations_controller'),
}
