/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

import BookmarkCreated from '#events/bookmark_created'
import FolderCreated from '#events/folder_created'
import MemberJoined from '#events/member_joined'
import MemberLeft from '#events/member_left'
import MemberRemoved from '#events/member_removed'
import PasswordResetRequested from '#events/password_reset_requested'
import UserRegistered from '#events/user_registered'

export const events = {
  BookmarkCreated: BookmarkCreated,
  FolderCreated: FolderCreated,
  MemberJoined: MemberJoined,
  MemberLeft: MemberLeft,
  MemberRemoved: MemberRemoved,
  PasswordResetRequested: PasswordResetRequested,
  UserRegistered: UserRegistered,
}
