/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const listeners = {
  CreateDefaultFolders: () => import('#listeners/create_default_folders'),
  SendPasswordResetEmail: () => import('#listeners/send_password_reset_email'),
  SendVerificationEmail: () => import('#listeners/send_verification_email'),
}
