/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'
import type { JSON } from '#types/db'
import type { AccessLevelType, RoleType } from '#enums/member'
import type { InvitationStatusType } from '#enums/invitation'
import type { NotificationData } from '#types/notifications'
import type { NotificationType } from '#enums/notification'
import type { PlanType } from '#enums/user'
import type { UserSettings } from '#types/user'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BookmarkSchema extends BaseModel {
  static $columns = ['browser', 'coverImageUrl', 'createdAt', 'description', 'domain', 'faviconUrl', 'folderId', 'id', 'isPinned', 'tags', 'title', 'updatedAt', 'url', 'userId', 'websiteName'] as const
  $columns = BookmarkSchema.$columns
  @column()
  declare browser: string
  @column()
  declare coverImageUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare domain: string
  @column()
  declare faviconUrl: string | null
  @column()
  declare folderId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isPinned: boolean
  @column()
  declare tags: JSON<string[]>
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare url: string
  @column()
  declare userId: string
  @column()
  declare websiteName: string | null
}

export class FolderSchema extends BaseModel {
  static $columns = ['bookmarkCount', 'createdAt', 'id', 'isSystem', 'memberCount', 'name', 'password', 'recentBookmarksImages', 'updatedAt', 'userId'] as const
  $columns = FolderSchema.$columns
  @column()
  declare bookmarkCount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isSystem: boolean
  @column()
  declare memberCount: number
  @column()
  declare name: string
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare recentBookmarksImages: JSON<string[]>
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class InvitationSchema extends BaseModel {
  static $columns = ['acceptedAt', 'accessLevel', 'createdAt', 'email', 'expiresAt', 'folderId', 'id', 'inviterId', 'status', 'token', 'updatedAt'] as const
  $columns = InvitationSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column()
  declare accessLevel: AccessLevelType
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare folderId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare inviterId: string
  @column()
  declare status: InvitationStatusType
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MemberSchema extends BaseModel {
  static $columns = ['accessLevel', 'createdAt', 'folderId', 'id', 'role', 'updatedAt', 'userId'] as const
  $columns = MemberSchema.$columns
  @column()
  declare accessLevel: AccessLevelType
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare folderId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare role: RoleType
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class NotificationSchema extends BaseModel {
  static $columns = ['createdAt', 'data', 'id', 'readAt', 'type', 'updatedAt', 'userId'] as const
  $columns = NotificationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare data: JSON<NotificationData>
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare type: NotificationType
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class OauthIdentitySchema extends BaseModel {
  static $columns = ['accessToken', 'createdAt', 'id', 'provider', 'providerId', 'refreshToken', 'updatedAt', 'userId'] as const
  $columns = OauthIdentitySchema.$columns
  @column()
  declare accessToken: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare provider: string
  @column()
  declare providerId: string
  @column()
  declare refreshToken: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class UserSchema extends BaseModel {
  static $columns = ['avatarUrl', 'createdAt', 'email', 'emailVerificationToken', 'emailVerificationTokenExpiresAt', 'firstName', 'id', 'isEmailVerified', 'lastName', 'location', 'password', 'plan', 'resetPasswordToken', 'resetPasswordTokenExpiresAt', 'settings', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare emailVerificationToken: string | null
  @column.dateTime()
  declare emailVerificationTokenExpiresAt: DateTime | null
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isEmailVerified: boolean | null
  @column()
  declare lastName: string
  @column()
  declare location: string | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare plan: PlanType
  @column()
  declare resetPasswordToken: string | null
  @column.dateTime()
  declare resetPasswordTokenExpiresAt: DateTime | null
  @column()
  declare settings: JSON<UserSettings>
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
