/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type BookmarkTransformer from '#transformers/bookmark_transformer'
import type FolderTransformer from '#transformers/folder_transformer'
import type InvitationTransformer from '#transformers/invitation_transformer'
import type MemberTransformer from '#transformers/member_transformer'
import type NotificationTransformer from '#transformers/notification_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Bookmark = InferData<BookmarkTransformer>
  export namespace Bookmark {
    export type Variants = InferVariants<BookmarkTransformer>
  }
  export type Folder = InferData<FolderTransformer>
  export namespace Folder {
    export type Variants = InferVariants<FolderTransformer>
  }
  export type Invitation = InferData<InvitationTransformer>
  export namespace Invitation {
    export type Variants = InferVariants<InvitationTransformer>
  }
  export type Member = InferData<MemberTransformer>
  export namespace Member {
    export type Variants = InferVariants<MemberTransformer>
  }
  export type Notification = InferData<NotificationTransformer>
  export namespace Notification {
    export type Variants = InferVariants<NotificationTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
